# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-knit-swift:
    runs-on: macos-latest
    strategy:
      matrix:
        swift-version: ["6.0", "6.1"]
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Build Knit (Swift ${{ matrix.swift-version }})
      run: swift build -v
    - name: Run Knit tests (Swift ${{ matrix.swift-version }})
      run: swift test -v
