# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-knit:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: swift-actions/setup-swift@v2.1.0
      with:
        swift-version: "5.10"
    - name: Build Knit
      run: swift build -v
    - name: Run Knit tests
      run: swift test -v
